apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cqi4dj32x-go
  janus-idp.io/tekton: cqi4dj32x-go
  backstage.io/kubernetes-id: cqi4dj32x-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cqi4dj32x-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
