apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cqi4dj32x-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cqi4dj32x-go 
  name: cqi4dj32x-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cqi4dj32x-go 
