apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cqi4dj32x-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:0b89c9779853e2fd24035e1bbe6862a648d0f02c@sha256:a91c44115a88f4435c2511c59a8fbbb5c25d72ef4dbc379916c6271147008ada
          name: container-image
